[package]
name = "annimate_desktop"
version = "0.1.0"
edition.workspace = true

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
annimate_core = { path = "../../annimate_core" }
itertools = { workspace = true }
tauri = { version = "1.5", features = [ "dialog-open", "process-exit", "dialog-save", "objc-exception", "path-all", "process-relaunch", "shell-open", "wry"], default-features = false }
serde = { workspace = true }
serde_json = "1.0"
tempfile = "3.10"
thiserror = { workspace = true }

[features]
custom-protocol = ["tauri/custom-protocol"]
