allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
autoInstallPeers: false
blockExoticSubdeps: true
minimumReleaseAge: 1440
overrides:
  '@typescript-eslint/typescript-estree>minimatch': ^10.2.1
strictDepBuilds: true
verifyDepsBeforeRun: prompt
