allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
autoInstallPeers: false
blockExoticSubdeps: true
minimumReleaseAge: 1440
strictDepBuilds: true
verifyDepsBeforeRun: prompt
minimumReleaseAgeExclude:
  # Renovate security update: vite@8.0.5
  - vite@8.0.5
