blank_issues_enabled: false
contact_links:
  - name: "\U0001F4A1 Idea"
    about: "Suggest a new feature to make Annimate better"
    url: https://github.com/matthias-stemmler/annimate/discussions/new?category=ideas
  - name: Start a Discussion
    about: "Start a discussion to share your experience with Annimate"
    url: https://github.com/matthias-stemmler/annimate/discussions/new/choose
  - name: Read the User Guide
    about: "Please make sure you have read the User Guide (especially the Troubleshooting section) before filing a bug report"
    url: https://matthias-stemmler.github.io/annimate/user-guide/