[package]
name = "annis_export_desktop"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
annis_export_core = { path = "../../annis_export_core", features = ["serde"] }
tauri = { version = "1.5", features = [ "process-relaunch", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
