name: Check (Cargo)

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tauri dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libwebkit2gtk-4.0-dev

      - name: Create dist dir
        # This prevents Tauri macros from panicking during `cargo clippy`
        run: mkdir annimate_desktop/dist

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --all-features --all-targets
