name: Test (pnpm)

on:
  - workflow_call
  - workflow_dispatch

env:
  # renovate: datasource=npm versioning=semver-coerced depName=corepack
  VERSION_COREPACK: 0.32.0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: annimate_desktop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install a specific version of corepack to make sure we have the latest signing keys
      - name: Install corepack
        run: npm install --global --force corepack@${{ env.VERSION_COREPACK }}

      - name: Enable corepack
        run: corepack enable

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: annimate_desktop/pnpm-lock.yaml
          node-version-file: annimate_desktop/.nvmrc

      - name: Install
        run: pnpm install

      - name: Run test
        run: pnpm test
