name: Test (Cargo)

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings

jobs:
  test:
    name: Test (on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-24.04, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Tauri dependencies (Linux only)
        if: runner.os == 'Linux'
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libwebkit2gtk-4.1-dev

      - name: Create dist dir
        # This prevents Tauri macros from panicking during `cargo clippy`
        run: mkdir annimate_desktop/dist

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --locked --all-features
