name: Unused dependencies (Cargo)

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings
  # renovate: datasource=crate versioning=semver-coerced depName=cargo-udeps
  VERSION_CARGO_UDEPS: 0.1.50

jobs:
  udeps:
    name: Unused dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tauri dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libwebkit2gtk-4.0-dev

      - name: Cache cargo-udeps
        id: cache-cargo-udeps
        uses: actions/cache@v4
        with:
          path: ~/.cargo/
          key: cargo-udeps-${{ env.VERSION_CARGO_UDEPS }}

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Install cargo-udeps
        if: ${{ !steps.cache-cargo-udeps.outputs.cache-hit }}
        run: cargo install cargo-udeps@${{ env.VERSION_CARGO_UDEPS }}

      - name: Check for unused dependencies
        run: cargo udeps
