name: Unused dependencies (Cargo)

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings
  # renovate: datasource=crate versioning=semver-coerced depName=cargo-udeps
  VERSION_CARGO_UDEPS: 0.1.57

jobs:
  udeps:
    name: Unused dependencies
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Tauri dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libwebkit2gtk-4.1-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Install cargo-udeps
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps@${{ env.VERSION_CARGO_UDEPS }}

      - name: Check for unused dependencies
        # cargo-udeps uses unstable flags, so we are supposed to use a nightly toolchain.
        # However, it internally uses cargo-the-library from crates.io, which aligns with the stable toolchain.
        # This means that it effectively uses stable cargo, but nightly rustc, which can cause incompatibilities.
        # Example: The `test` cfg was turned into a userspace check-cfg in nightly rustc, while stable cargo still assumed it was a well-known cfg.
        # To mitigate this issue, we set RUSTC_BOOTSTRAP=1 to be able to use unstable flags with stable rustc.
        run: RUSTC_BOOTSTRAP=1 cargo udeps
